### ISSUE TITLE
关于Gitalk和Vueress的问题！

### ISSUE THREAD

**Issue by demigodliu** [dongyuanxin/blog#155]
您好，我想请问一下，你的博客，Gitalk是放在文章最下方，位于上一篇/下一篇的下面。但是为什么我搭建的，Gitalk虽然在文章的下方，但却在上一篇，下一篇的上方呢？怎么让Gitalk位于最下方呢？

![image.png](https://i.loli.net/2019/09/01/LmnUQzHfr5ceOXT.png)

**Comment by dongyuanxin** [comment]
试试这个插件：[vuepress-plugin-comment](https://github.com/dongyuanxin/vuepress-plugin-comment/)

**Comment by demigodliu** [comment]
@dongyuanxin 昨晚上已经弄好啦~谢谢大佬

**Comment by dongyuanxin** [comment]
> @dongyuanxin 昨晚上已经弄好啦~谢谢大佬

不客气～
