### ISSUE TITLE
``Blog''ing sounds fun. How about an english readme.md ?

### ISSUE THREAD

**Issue by fdenzer** [dongyuanxin/blog#20]
as title

**Comment by dongyuanxin** [comment]
Thanks for your suggestion. I will support internationalization recently.

**Comment by dongyuanxin** [comment]
> as title

Thanks for your suggestion. I will support internationalization recently.

**Comment by dongyuanxin** [comment]
Hi, @fdenzer . English readme is here : https://xin-tan.com/en/ 
By the way, I fix html property--`lang`. So, Chrome translation plugin could recognize page language and translate automatically.
