### ISSUE TITLE
「评论」网站信息

### ISSUE THREAD

**Issue by dongyuanxin** [dongyuanxin/blog#88]
网站信息：https://xin-tan.com/about/

**Comment by shiyisen321** [comment]
这个博客怎么搭的呀，

**Comment by dongyuanxin** [comment]
> @shiyisen321
> 这个博客怎么搭的呀，

[vuepress@1.0版本](https://v1.vuepress.vuejs.org/), 评论是[vuepress-plugin-comment](https://github.com/dongyuanxin/vuepress-plugin-comment), 关于导航栏和侧边栏可以参考我的github仓库

**Comment by MrNickLock** [comment]
哇，理想中的博客，已star已fork！

**Comment by dongyuanxin** [comment]
> @MrNickLock
> 哇，理想中的博客，已star已fork！

欢迎常来，网站每年都有大更新^_^

**Comment by leejiawang** [comment]
ad主题怎么改成你这样的侧边栏？求回答

**Comment by dongyuanxin** [comment]
> @leejiawang
> ad主题怎么改成你这样的侧边栏？求回答

ad主题目前改不了

**Comment by Hewie8023** [comment]
你好，使用这个gitalk存在：Error: Validation Failed.这个错误。

**Comment by dongyuanxin** [comment]
> @Hewie8023
> 你好，使用这个gitalk存在：Error: Validation Failed.这个错误。

github要授权

**Comment by Hewie8023** [comment]
> @dongyuanxin
> > @Hewie8023
> > 你好，使用这个gitalk存在：Error: Validation Failed.这个错误。
> 
> github要授权

这个是说id不能超过50个字符好像，，但是我已经用了你配置里那个id字段了，，
